name: responsive_login_ui
description: Responsive SignUp & Login Screens

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^3.0.1
  lottie: ^1.4.2
  flutter_gif: any
  google_maps_flutter: ^2.2.4
  location: ^4.4.0

<<<<<<< HEAD
  flutter_switch: ^0.3.2

=======
>>>>>>> fbbe6b76034188446022129f432fee451f9e73eb
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
<<<<<<< HEAD
  assets:
    - assets/logo.png
    - assets/pic1.jpg
    - assets/ambulance.png
    - assets/person.png
=======

  assets:
    - assets/
>>>>>>> fbbe6b76034188446022129f432fee451f9e73eb

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
<<<<<<< HEAD
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700
=======
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
>>>>>>> fbbe6b76034188446022129f432fee451f9e73eb
